Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|

    master.vm.box = "ubuntu/jammy64"

    master.vm.network "private_network", ip: "192.168.43.10"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.memory = 8192
      vb.cpus = 4
    end

  end

end