Vagrant.configure("2") do |config|

  config.vm.define "worker1" do |worker|

    worker.vm.box = "ubuntu/jammy64"

    worker.vm.hostname = "worker1"

    worker.vm.network "private_network", ip: "192.168.43.20"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "worker1"
      vb.memory = 4096
      vb.cpus = 2
    end

  end

end