name: Cloud Native Security CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  docker-security:
    name: Docker Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hadolint Dockerfile check
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/Dockerfile

      - name: Build Docker image
        run: |
          docker build -t projet-cloud-native-app ./app

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: projet-cloud-native-app
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH